### PR TITLE
Refactor and allow overriding of argument formatting

### LINKED ISSUE #309: "ExceptionFormatter"/"format_kwargs": provide customization for special application types
As "https://github.com/zopefoundation/Zope/issues/837" describes, exception information is not optimal in a Zope context. This is because many objects are so called acquisition wrappers. `chameleon.utils.format_kwargs` does (understandably) not know this type and uses the uninformative representation via type name and address.

If `chameleon` would provide customization for `ExceptionFormatter` and/or `format_kwargs`, an integration could ensure proper representation for types with special importance, such as "acquisition wrapper"s for Zope.

### PR DESCRIPTION
**Pull request by malthe**
This fixes #309.

### CODE REVIEW

**Comment by malthe** [comment]
@d-maurer yes, that's perhaps a good idea all things considered.

**Comment by malthe** [comment]
@d-maurer I have adressed the one place where this might theoretically throw an exception here: 8c8b24d685ecdee095d553fc244e965aaa24ea3f.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-5-27 01:44 -0700:
>@d-maurer I have adressed the one place where this might theoretically throw an exception here: 8c8b24d685ecdee095d553fc244e965aaa24ea3f.

Likely, my comment was not sufficiently precise. I did not mean this place
(even though your change will not introduce problems).

My motivation was: now that `value_repr` is a customizable function,
it is possible that it raises an exception in some situations.
You might want to handle this case in `ExceptionFormatter`
(forermly, you had such exception handling there).

Of course, you could require that `value_repr` handles all its exceptions
itself. In this case, I would add a corresponding description.

**Comment by malthe** [comment]
(I added a note that the function must be safe to call for any value.)

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-5-27 02:23 -0700:
>(I added a note that the function must be safe to call for any value.)

Thank you for your quick response to my report!

**Pull request merged**
