### PR TITLE
Run tests on GitHub Actions.

### PR DESCRIPTION
**Pull request by icemac**
The changes where made using https://github.com/zopefoundation/meta/tree/master/config. I kept the Python 2 support for now and did not run isort and flake8.

### CODE REVIEW

**Comment by icemac** [comment]
This PR has to be merged to activate GitHub Actions in this repository. See the results of the GitHub Actions run in my fork: https://github.com/icemac/chameleon/actions

**Comment by malthe** [comment]
@icemac what are those "." doing at the end of your commit messages ...

**Comment by icemac** [comment]
> @icemac what are those "." doing at the end of your commit messages ...

My commit messages are sentences which I usually and with a ".".

**Comment by dataflake** [comment]
I'm sure you already noticed that py35 is running twice, right?

**Comment by malthe** [comment]
Now I did damn

**Comment by icemac** [comment]
> I'm sure you already noticed that py35 is running twice, right?

Hm, the result of manually tempering in a generated file.

Are there plans to drop support for Python 2.7 up to 3.6, as we are currently doing it in `zopefoundation`?

**Comment by dataflake** [comment]
> > I'm sure you already noticed that py35 is running twice, right?
> 
> Hm, the result of manually tempering in a generated file.

@icemac I have projects where I just re-added the no-longer-supported environments in `.meta.toml`. The only thing that meta/config is doing that needs correction (or a configuration flag) is always setting `universal = 0` in `setup.cfg`.

**Comment by dataflake** [comment]
P.S.: Here is a sample that restores the old behavior: https://github.com/dataflake/Products.LocalFS/blob/master/.meta.toml

**Comment by malthe** [comment]
I think we should should drop those unsupported Pythons yeah. The old releases are still available of course.

**Comment by icemac** [comment]
I'll try to present you a PR removing support for old Python version.

**Comment by icemac** [comment]
> I'll try to present you a PR removing support for old Python version.

See #364.

**Pull request merged**
