### PR TITLE
Make scope class dict-like

### PR DESCRIPTION
**Pull request by malthe**
This fixes issue #305.

### CODE REVIEW

**Comment by malthe** [comment]
@icemac wdyt ^^^

**Comment by icemac** [comment]
I have no idea. I did not understand the issue in the first place.

**Review by d-maurer — COMMENTED** [review]
The changes in `utils` seem promising -- apparently, they correctly look up names first in the current and then in the root scope.
The methods `keys`, `values` and `items` do not employ "global" logic -- but likely they are not needed anyway.

I cannot say much for the apparent replacements of `*item` by `*name` at other places. It is possible that the mapping of `Zope.tales` to `chameleon.tales` (used by `Zope`) would need to adapt to this change.

**Comment by malthe** [comment]
@d-maurer – I will bump the version up to 3.10.x with this change so that there is a chance to react on compatibility issues.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2022-4-6 07:53 -0700:
***@***.*** – I will bump the version up to 3.10.x with this change so that there is a chance to react on compatibility issues.


One of the `Products.PageTemplates` tests fail with the new version.
It calls `chameleon.utils.Scope.get` and expects `None`
to indicate a non existing key - instead a `KeyError` is raised.

Users are familiar with the behavior of `dict.get` (return
`None` for non existing keys);
maybe, `Scope.get` should behave in the same way?

**Comment by malthe** [comment]
Oh yes that definitely sounds like a bug.

**Pull request merged**
