### PR TITLE
Fix double dollar escaping

### LINKED ISSUE #282: String expression ending in $$ is not parsed correctly
According to the language reference and the old behavior in Zope 2 (which used `zope.tales` instead of `chameleon.tales`), a `$$` in a string expression should result in a single `$`. However. this is only the case if there are `non_dollar` characters following the `$$`:

    In [2]: chameleon.tales.test(chameleon.tales.StringExpr('$$test'))
    Out[2]: '$test'

    In [3]: chameleon.tales.test(chameleon.tales.StringExpr('test$$'))
    Out[3]: 'test$$'

I posted this issue on https://github.com/zopefoundation/Zope/issues/510 because in my opinion it is a critical issue for Zope (and because I was on the wrong track first, thinking `zope.tales` was used when parsing Page Templates, before finding out that `chameleon.tales` is actually used).

### PR DESCRIPTION
**Pull request by malthe**
Fixes #282

### CODE REVIEW

**Comment by viktordick** [comment]
I tried to expand the regular expression to cover `$$`, `\$`, `${name}` or `$name`, with the first two not depending on whether anything follows. However, this breaks the doctest

    >>> result = test(StringExpr(\"\"\"
    ... function($$, oid) {
    ...     $('#' + oid).autocomplete({source: ${'source'}});
    ... }
    ... \"\"\"))

    >>> 'source: source' in result
    True

    The double-dollar escape does not affect non-interpolation
    expressions.

    >>> 'function($$, oid)' in result
    True

Can you say what is meant by "non-interpolation expressions"? I would expect that in this case also the `$$` is replaced by `$`.

**Comment by malthe** [comment]
I updated the PR to cover both of your cases. This might be the right fix then, but I haven't checked any `zope.tales` tests to verify.

**Comment by viktordick** [comment]
The doctest I mentioned is from `chameleon.tales`, line 414. And since the test still succeeds, I think this is not the correct fix - if I read the docs correctly (and if we want to maintain backwards compatibility with zope.tales), `$$` should always be replaced by `$` and that doctest should fail (and be replaced by another one)

**Comment by viktordick** [comment]
If I see correctly, with that fix a `$$` would be treated differently depending on whether after that another `$name` follows or not. So for `key=value`

    test $$ ${key}

would result in

    test $$ value

while

    test $$ value

would result in

    test $ value

**Comment by malthe** [comment]
That behavior seems to have been added to fix https://github.com/malthe/chameleon/issues/265.

> double-dollar escape does not affect non-interpolation expressions.

I guess the idea is that you don't need to escape a non-interpolation expression. But if `zope.tales` does it differently, then perhaps it should be done differently.

**Comment by viktordick** [comment]
My suggestion would be to change `braces_optional_regex` in `compiler.py:279` to something like

    r'(\$\$|\\\$|\${(?P<expression>.*)}|\$(?P<variable>[A-Za-z][A-Za-z0-9_]*))'

and replace the mentioned test by another one. The `braces_required_regex` should also be adjusted in a similar way I guess

**Comment by malthe** [comment]
The following also seems to fix the situation but then breaking the test in `chameleon.tales`:
```diff
diff --git a/src/chameleon/compiler.py b/src/chameleon/compiler.py
index 0bf9b14..4eab3e7 100644
--- a/src/chameleon/compiler.py
+++ b/src/chameleon/compiler.py
@@ -335,6 +335,7 @@ class Interpolator(object):
                 part = part + '$'
 
             if part:
+                part = part.replace('$$', '$')
                 node = ast.Str(s=part)
                 nodes.append(node)
```

**Comment by viktordick** [comment]
I did not see #265 because I only searched still open issues before filing a new one. But if I understand the original poster correctly, the PR did not fix his issue - he also expected `$$` to always be replaced by `$`. His problem is similar to mine, he expected `$$.each` to be parsed to give the jQuery function `$.each`, I expect `$$.ajax` to give `$.ajax`. But I guess he never repsonded if the PR fixed his issue or not.

**Comment by viktordick** [comment]
> The following also seems to fix the situation but then breaking the test in `chameleon.tales`:
> 
> ```diff
> diff --git a/src/chameleon/compiler.py b/src/chameleon/compiler.py
> index 0bf9b14..4eab3e7 100644
> --- a/src/chameleon/compiler.py
> +++ b/src/chameleon/compiler.py
> @@ -335,6 +335,7 @@ class Interpolator(object):
>                  part = part + '$'
>  
>              if part:
> +                part = part.replace('$$', '$')
>                  node = ast.Str(s=part)
>                  nodes.append(node)
> ```

This seems to fix it, but then the handling of `$$` is spread out over different cases. And `\$` has the same problem, which should also be addressed.

I would suggest to instead change the regex, like mentioned above, to "either two dollars, a backslash and a dollar, a dollar with an identifier in braces or a dollar with an identifier without braces". This seems clearer to me.

**Comment by viktordick** [comment]
Actually, I looked into the docs again and it does not say that `string:` expressions should treat `\$` as escaping a `$`. Maybe this should be dropped or the docs should be adjusted?

**Comment by viktordick** [comment]
I guess your suggestion (in this pull request, together with the addition suggested above) boils down to "_Search for the first occurence of either a token or an escaped dollar, but only if it might be mistaken for a token if we do not include it. If it is an escaped dollar, replace it accordingly and move the starting point for the next search. Also, replace any other occurences of `$$` up to that point. If there is no more match, also do such a replacement on the remaining string_".

My suggestion, on the other hand, boils down to the simpler "_Search for the first occurence of either a token or an escaped dollar. If it is an escaped dollar, replace it accordingly and move the starting point for the next search_".

I think my suggestion is simpler, but as long as the issue gets fixed I'm happy either way. This leaves the question of what to do about `\$`.

**Comment by malthe** [comment]
I have removed support for backslash-based escaping entirely.

The behavior should now be consistent with Zope's. Can you verify the updated (force pushed) patch?

**Comment by viktordick** [comment]
Looks good to me! This allows me to get to the next error (which is not in TALES at the moment) when trying to port a Zope 2.13 application to Zope 4. Thanks!

**Pull request merged**
