### PR TITLE
Add the 'macroname' variable.

### LINKED ISSUE #238: Support for `macroname`?
The Zope TAL implementation [automatically provides the `macroname` variable](https://github.com/zopefoundation/zope.tal/blob/master/src/zope/tal/talinterpreter.py#L895) during the scope of execution of the macro, although this seems to be undocumented. However, this is used by some existing Zope templates, such as [the main layout of zope.app.rotterdam](https://github.com/zopefoundation/zope.app.rotterdam/blob/master/src/zope/app/rotterdam/template_tablelayout.pt#L95). Chameleon doesn't provide this variable, preventing it from running such templates.

Is this something Chameleon could/would/should do? If so, I would be happy to work on a PR to add that (although I might need some guidance).

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #238.

The test files are lifted directly from zope.tal.

It didn't seem necessary to use `wrap`, the Define wraps a node itself. The code generated for `render_page` in the test example is now this:
```python
_static_4339677264 = u'page'
...
  def render_page(...):
        ...
        try:
            getitem = econtext.__getitem__
            get = econtext.get
            __backup_macroname_4337608536 = get('macroname', __marker)

            # <Static value=<_ast.Str object at 0x102aa3850> name=None at 102aa38d0> -> __value
            __value = _static_4339677264
            econtext['macroname'] = __value
            __append(u'\n  ')
            if (__slot_name is None):
                pass
            else:
                __slot_name(__stream, econtext.copy(), rcontext)
            __append(u'\n')
            if (__backup_macroname_4337608536 is __marker):
                del econtext['macroname']
            else:
                econtext['macroname'] = __backup_macroname_4337608536
        except:
            rcontext.setdefault('__error__', []).append((__token + (_exc_info()[1], )))
            raise
```

### CODE REVIEW

**Comment by malthe** [comment]
Awesome!

**Comment by jamadden** [comment]
Thanks! This gets `zope.app.rotterdam` rendering with Chameleon, but the tests I'm looking at still don't pass (for reasons that are unclear).

**Comment by malthe** [comment]
OK let's wait with a release then until the tests pass! I also have some few minor optimizations that I'd like to get in before calling it 3.2.

**Comment by jamadden** [comment]
And the reason is that the `macroname` isn't taking on the same value in Chameleon as it is in zope.tal.

Given this block:
```html
               <metal:slot define-slot="navigators">
                <div id="navigators" metal:define-macro="navigators">
                    <!-- Navigation tree box -->
                    <metal:tree use-macro="context/@@standard_macros/navigation_tree_box" />
					<span tal:content="macroname"></span>
                    <tal:block condition="python: macroname == 'view'">
...
```

The `macroname` is `view` under zope.tal, but `navigators` under Chameleon.

**Comment by jamadden** [comment]
We missed a layer of indirection here, I think. In zope.tal, the `macroname` is assigned at the time the `metal:use-macro` is executed, not at the time the macro is defined. This block occurs in the context of `<html metal:use-macro="context/@@standard_macros/view"`, so when https://github.com/zopefoundation/zope.tal/blob/master/src/zope/tal/talinterpreter.py#L897 executes, `macroname` is bound to `view`.

**Comment by jamadden** [comment]
OK, I think I've got it. Fresh PR coming up.

**Pull request merged**
