### PR TITLE
remove use relative imports

### PR DESCRIPTION
**Pull request by kloczek**

### CODE REVIEW

**Comment by malthe** [comment]
What's the value in absolute imports?

**Comment by malthe** [comment]
I honestly don't see the particular benefit, see also https://peps.python.org/pep-0328/#rationale-for-relative-imports.

The system calls very cheap. I think counting system calls is a thing really only when you want to do 100's of them per second, repeatedly, such as when serving up web requests and such.

Perhaps https://peps.python.org/pep-0690/ is a better approach to improving Python startup performance, lazy-loading rather than optimize each individual load, the point being that doing less is better than doing more, faster.

**Comment by kloczek** [comment]
None of those PEPs shows any benefits. Only because some PEP allows use something it does not mean that it should be used.

- try to have look across most frequently used modules like `setuptools`, `pip`, `pytest`, `sphinx` or few other. None are using relative imports
- relative imports in case of modules with DSOs breaks testing those modules without install because DSOs must be in the same in the same directory where are .py files
- in many cases relative imports are breaking pytest based test suites.

As I wrote already using relative imports adds few additional syscalls on each import.
I have already packaged +1.2k modules as rpm packages and only handful of modules uses relative imports (about 10). In past year number of such modules decreased.

**Comment by kloczek** [comment]
Thank you 👍

**Pull request merged**
